"""
harness_classifier.py  v6.1
===========================
AI-Driven Pre-ECU Harness Integrity and Routing Validation System
Ashok Leyland — Chassis Assembly Line 2

v6.1 fixes applied (all 10 review issues resolved)
────────────────────────────────────────────────────
  FIX-1  Temporal feature columns explicitly named and appended to feat_cols
         (Issue #1 — feature count mismatch after temporal features)
  FIX-2  demo_inference() uses the same featurise() helper as the training
         pipeline, including temporal columns — no more dimensional mismatch
         (Issue #2 — demo inference feature mismatch)
  FIX-3  feat_cols updated AFTER selector is applied, using get_support() on
         the fully-named list that now includes temporal cols (Issue #3)
  FIX-4  ENABLE_ENSEMBLE_CALIBRATION = False by default; CalibratedClassifierCV
         wrapping the ensemble is guarded by this flag (Issue #4)
  FIX-5  evaluate_persistent_faults() removed from classifier evaluation;
         FaultConfirmer kept for dashboard / inference use only (Issue #5)
  FIX-6  Branch groups in demo_inference() fixed to [0,1,2],[3,4,5],[6,7,8],
         [9,10] matching the generator's BRANCH_GROUPS (Issue #6)
  FIX-7  ROC-AUC reorders probability columns to match FAULT_LABELS order
         before calling roc_auc_score (Issue #7)
  FIX-8  Temporal features are scaled with a dedicated StandardScaler before
         SelectKBest to prevent dominance over static features (Issue #8)
  FIX-9  selector.pkl saved alongside model artifacts; loaded in inference and
         dashboard via model_metadata (Issue #9)
  FIX-10 Report header version bump to v6.1 (Issue #10)

Earlier v6 fixes retained:
  FIX-A  worst_node_idx excluded (leakage ablation)
  FIX-B  signal_uniformity = mean(per-branch variance)
  FIX-C  Physics-informed severity formula
  FIX-D  SHAP documented as surrogate explainability for ensemble
  FIX-E  FaultConfirmer debounce class
  FIX-F  Ensemble calibration flag (now off by default per FIX-4)
  FIX-G  Accuracy wording corrected in report header
  FIX-H  Node count (NUM_NODES=12) clarified in metadata
"""

import os, csv, pickle, warnings
import numpy as np
from collections import Counter
from datetime import datetime

warnings.filterwarnings("ignore")

# ── DEPENDENCIES ──────────────────────────────────────────────────────────────
try:
    from sklearn.ensemble import RandomForestClassifier, VotingClassifier
    from sklearn.svm import SVC
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.preprocessing import LabelEncoder, StandardScaler, label_binarize
    from sklearn.calibration import CalibratedClassifierCV, calibration_curve
    from sklearn.pipeline import Pipeline
    from sklearn.model_selection import (train_test_split, cross_val_score,
                                         StratifiedKFold)
    from sklearn.metrics import (classification_report, confusion_matrix,
                                 accuracy_score, matthews_corrcoef,
                                 roc_auc_score, brier_score_loss)
    from sklearn.decomposition import PCA
    from sklearn.feature_selection import mutual_info_classif, SelectKBest
except ImportError:
    print("[ERROR] pip install scikit-learn --break-system-packages"); raise

try:
    import xgboost as xgb
    XGB_OK = True
except ImportError:
    XGB_OK = False
    print("[WARN] XGBoost not installed — will skip.")

try:
    import shap
    SHAP_OK = True
except ImportError:
    SHAP_OK = False
    print("[WARN] SHAP not installed — skipping SHAP plots.")

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    PLOT = True
except ImportError:
    PLOT = False

# ── CONFIG ────────────────────────────────────────────────────────────────────
OUT          = "classifier_output"
DATASET_PATH = "dataset_output/harness_dataset_realistic.csv"
os.makedirs(OUT, exist_ok=True)

FAULT_LABELS = [
    "HEALTHY", "OPEN_CIRCUIT", "SHORT_TO_GROUND",
    "WIRE_WIRE_SHORT", "HIGH_RESISTANCE", "ROUTING_MISMATCH",
]
LOCATION_LABELS = ["Branch_A", "Branch_B", "Branch_C", "Branch_D", "None"]

COLORS = ["#27AE60", "#C0392B", "#B86B00", "#5B3FA6", "#2471A3", "#E74C3C"]
CONFIDENCE_THRESHOLD = 0.75

# FIX-A: worst_node_idx excluded; FIX-B: signal_uniformity redefined in generator
LEAKAGE_COLS = {"severity", "fault_detected", "worst_node_idx"}

# FIX-D: surrogate explainability model (RF used for SHAP, ensemble for prediction)
FINAL_EXPLAIN_MODEL = "Random Forest"
FINAL_PREDICT_MODEL = "Ensemble (RF+XGB+SVM)"

# FIX-4: guard expensive nested calibration — set True only for publication runs
ENABLE_ENSEMBLE_CALIBRATION = False

# Number of temporal steps generated by dataset generator (must match generator)
N_TEMPORAL_STEPS = 5


# ── FIX-E: PERSISTENT FAULT CONFIRMATION ─────────────────────────────────────
class FaultConfirmer:
    """
    Debounce logic: confirm a fault only after N consecutive identical readings.
    Used in dashboard / real-time inference only (not in shuffled evaluation).
    """
    def __init__(self, n_required=3):
        self.n_required = n_required
        self._last  = None
        self._count = 0

    def update(self, label):
        if label == self._last:
            self._count += 1
        else:
            self._last  = label
            self._count = 1
        if self._count >= self.n_required:
            return label
        return None

    def reset(self):
        self._last = None; self._count = 0


# ── LOAD DATA ─────────────────────────────────────────────────────────────────
def load_data(path):
    print(f"Loading: {path}")
    if not os.path.exists(path):
        print("[ERROR] Dataset not found. Run harness_dataset_generator.py first.")
        raise FileNotFoundError(path)
    rows = []
    with open(path, "r") as f:
        for row in csv.DictReader(f):
            rows.append(row)
    print(f"  {len(rows)} samples, {len(rows[0])} columns")
    return rows


# ── FIX-1 + FIX-3: extract_features with explicit temporal column names ───────
def extract_features(rows, fset="engineered"):
    """
    Returns X (ndarray), y (ndarray), feat_cols (list of str).

    FIX-1: temporal columns are explicitly named and appended to feat_cols so
           X.shape[1] == len(feat_cols) at all times.
    FIX-3: feat_cols is complete before SelectKBest is called in main(), so
           get_support(indices=True) correctly maps back to named columns.
    """
    if fset == "voltage_only":
        static_cols = [f"V_N{n}" for n in range(1, 12)]
    else:
        all_candidate = (
            [f"V_N{n}" for n in range(1, 12)] +
            [f"DEV_N{n}_pct" for n in range(1, 12)] +
            [f"I_N{n}_mA" for n in [2, 3, 5, 6, 8, 9, 11]] +
            [
                "V_min", "V_max", "V_range", "V_mean", "V_std",
                "dev_max_abs", "nodes_above_threshold",
                "N5_N6_diff", "N2_N3_diff", "N8_N9_diff",
                "worst_node_isolation", "temperature_C",
                "routing_signature", "branch_symmetry_error",
                "isolation_index", "signal_uniformity",
                "max_branch_delta", "cross_coupling_estimate",
            ]
        )
        sample_keys = set(rows[0].keys())
        static_cols = [c for c in all_candidate
                       if c not in LEAKAGE_COLS and c in sample_keys]

    # FIX-1: build explicit temporal column names (4 stats × 11 nodes)
    has_temporal = f"V_N1_t0" in rows[0]
    temporal_cols = []
    if has_temporal:
        for n in range(1, 12):
            temporal_cols.extend([
                f"V_N{n}_tmean",
                f"V_N{n}_tstd",
                f"V_N{n}_tdelta",
                f"V_N{n}_trange",
            ])

    feat_cols = static_cols + temporal_cols  # complete, named list

    X = []
    for r in rows:
        row_feats = [float(r.get(c, 0.0)) for c in static_cols]
        if has_temporal:
            for n in range(1, 12):
                try:
                    seq = np.array([float(r[f"V_N{n}_t{t}"])
                                    for t in range(N_TEMPORAL_STEPS)])
                    row_feats.extend([
                        float(seq.mean()),
                        float(seq.std()),
                        float(seq[-1] - seq[0]),
                        float(seq.max() - seq.min()),
                    ])
                except (KeyError, ValueError):
                    row_feats.extend([0.0, 0.0, 0.0, 0.0])
        X.append(row_feats)

    X = np.array(X, dtype=np.float64)
    y = np.array([r["fault_label"] for r in rows])

    assert X.shape[1] == len(feat_cols), (
        f"[BUG] X.shape[1]={X.shape[1]} != len(feat_cols)={len(feat_cols)}"
    )
    return X, y, feat_cols, static_cols, temporal_cols


def extract_location_labels(rows):
    def to_branch(loc):
        nodes_in_loc = [int(n) for n in loc.split("_") if n.isdigit()]
        for n in nodes_in_loc:
            if n in [1, 2, 3]:  return "Branch_A"
            if n in [4, 5, 6]:  return "Branch_B"
            if n in [7, 8, 9]:  return "Branch_C"
            if n in [10, 11]:   return "Branch_D"
        return "None"
    return np.array([to_branch(r.get("fault_location", "None")) for r in rows])


# ── FIX-C: PHYSICS SEVERITY (mirrors generator formula) ──────────────────────
def compute_physics_severity(devs, branch_sym, iso_idx, routing_sig):
    da  = [abs(d) for d in devs]
    wvd = min(1.0, max(da) / 100.0)
    bi  = min(1.0, branch_sym / 1.0)
    ie  = min(1.0, abs(1.0 - iso_idx))
    ra  = min(1.0, routing_sig / 2.0)
    return round(min(100.0, (0.45 * wvd + 0.25 * bi + 0.15 * ie + 0.15 * ra) * 100.0), 2)


# ── BUILD MODELS ──────────────────────────────────────────────────────────────
def build_models():
    rf = RandomForestClassifier(
        n_estimators=300, max_depth=None,
        min_samples_split=2, random_state=42, n_jobs=-1)

    dt = DecisionTreeClassifier(
        max_depth=15, min_samples_split=4, random_state=42)

    knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)

    svm_pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("svm", CalibratedClassifierCV(
            SVC(kernel="rbf", C=10, gamma="scale",
                probability=True, random_state=42),
            cv=3, method="isotonic")),
    ])

    models = {
        "Random Forest": rf,
        "Decision Tree": dt,
        "k-NN (k=5)":    knn,
        "SVM (RBF)":     svm_pipeline,
    }

    if XGB_OK:
        xgb_model = xgb.XGBClassifier(
            n_estimators=300, max_depth=6, learning_rate=0.1,
            subsample=0.8, colsample_bytree=0.8,
            eval_metric="mlogloss", random_state=42, n_jobs=-1)
        models["XGBoost"] = xgb_model

        base_ensemble = VotingClassifier(
            estimators=[
                ("rf", RandomForestClassifier(
                    n_estimators=200, random_state=42, n_jobs=-1)),
                ("xgb", xgb.XGBClassifier(
                    n_estimators=200, max_depth=5, learning_rate=0.1,
                    eval_metric="mlogloss", random_state=42, n_jobs=-1)),
                ("svm", Pipeline([
                    ("scaler", StandardScaler()),
                    ("svm", CalibratedClassifierCV(
                        SVC(kernel="rbf", C=10, gamma="scale",
                            probability=True, random_state=42),
                        cv=3, method="isotonic")),
                ])),
            ],
            voting="soft")

        # FIX-4: calibration off by default — too expensive unless explicitly enabled
        if ENABLE_ENSEMBLE_CALIBRATION:
            ensemble = CalibratedClassifierCV(base_ensemble, cv=3, method="isotonic")
        else:
            ensemble = base_ensemble

        models[FINAL_PREDICT_MODEL] = ensemble

    return models


# ── TRAIN & EVALUATE ──────────────────────────────────────────────────────────
def train_evaluate(X_train, X_test, y_train, y_test, feat_cols, le):
    scaler = StandardScaler()
    scaler.fit(X_train)

    y_tr_enc = le.transform(y_train)
    y_te_enc = le.transform(y_test)

    models = build_models()
    results = {}

    print("\n" + "=" * 60)
    print("MODEL TRAINING & EVALUATION  [v6.1 — all fixes applied]")
    print("=" * 60)

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    for name, model in models.items():
        print(f"\n[{name}] Training...")
        is_xgb = name == "XGBoost"
        ytr = y_tr_enc if is_xgb else y_train
        yte = y_te_enc if is_xgb else y_test

        model.fit(X_train, ytr)

        y_pred_raw = model.predict(X_test)
        if is_xgb:
            y_pred = le.inverse_transform(y_pred_raw)
        else:
            y_pred = y_pred_raw

        y_prob = model.predict_proba(X_test)

        # FIX-7: reorder probability columns to match FAULT_LABELS order
        if is_xgb:
            xgb_classes = [le.inverse_transform([c])[0] for c in model.classes_]
            col_order = [xgb_classes.index(fl)
                         for fl in FAULT_LABELS if fl in xgb_classes]
            y_prob = y_prob[:, col_order]
        else:
            model_classes = list(model.classes_)
            col_order = []
            for fl in FAULT_LABELS:
                if fl in model_classes:
                    col_order.append(model_classes.index(fl))
            if len(col_order) == len(FAULT_LABELS):
                y_prob = y_prob[:, col_order]

        y_pred_thresh = np.array([
            p if y_prob[i].max() >= CONFIDENCE_THRESHOLD else "UNCERTAIN"
            for i, p in enumerate(y_pred)
        ])

        acc   = accuracy_score(y_test, y_pred)
        mask  = y_pred_thresh != "UNCERTAIN"
        acc_t = accuracy_score(y_test[mask], y_pred_thresh[mask]) if mask.any() else acc
        n_unc = int((~mask).sum())

        cv    = cross_val_score(model, X_train, ytr,
                                cv=skf, scoring="accuracy", n_jobs=-1)
        cv_m, cv_s = cv.mean(), cv.std()

        mcc = matthews_corrcoef(y_test, y_pred)
        try:
            y_bin = label_binarize(y_test, classes=FAULT_LABELS)
            auc   = roc_auc_score(y_bin, y_prob, multi_class="ovr", average="macro")
        except Exception:
            auc = float("nan")

        class_conf_acc = {}
        for fl in FAULT_LABELS:
            mask_c = (np.array(y_test) == fl) & mask
            class_conf_acc[fl] = (accuracy_score(np.array(y_test)[mask_c],
                                                  y_pred_thresh[mask_c])
                                  if mask_c.any() else float("nan"))

        cm = confusion_matrix(y_test, y_pred, labels=FAULT_LABELS)
        cr = classification_report(y_test, y_pred, labels=FAULT_LABELS)

        # FIX-5: persistent fault metric REMOVED from evaluation
        # (shuffled test set has no temporal order — metric is meaningless)
        # FaultConfirmer is only used in dashboard/inference.

        print(f"  Raw Accuracy     : {acc * 100:.2f}%")
        print(f"  Confident Acc    : {acc_t * 100:.2f}%  "
              f"(UNCERTAIN: {n_unc}/{len(y_pred)} = {n_unc/len(y_pred)*100:.1f}%)")
        print(f"  CV Accuracy      : {cv_m * 100:.2f}% +/- {cv_s * 100:.2f}%")
        print(f"  MCC              : {mcc:.4f}")
        print(f"  ROC-AUC (OvR)    : {auc:.4f}")

        results[name] = dict(
            model=model, acc=acc, acc_thresh=acc_t,
            cv_mean=cv_m, cv_std=cv_s, cm=cm, cr=cr,
            y_pred=y_pred, y_pred_thresh=y_pred_thresh,
            y_prob=y_prob, n_uncertain=n_unc,
            scaled=False,
            mcc=mcc, auc=auc, class_conf_acc=class_conf_acc,
            is_xgb=is_xgb,
        )

    return results, scaler


# ── LOCATION MODEL ────────────────────────────────────────────────────────────
def train_location_model(X_train, y_loc_train):
    print("\n[Fault Location Predictor] Training (Branch_A/B/C/D)...")
    loc_model = RandomForestClassifier(
        n_estimators=200, max_depth=10, random_state=42, n_jobs=-1)
    loc_model.fit(X_train, y_loc_train)
    return loc_model


# ── CALIBRATION DIAGNOSTICS ──────────────────────────────────────────────────
def run_calibration_diagnostics(results, y_test):
    print("\n  [Calibration] Computing diagnostics...")
    report_lines = [
        "=" * 70,
        "PROBABILITY CALIBRATION REPORT  v6.1",
        "AI-Driven Pre-ECU Harness Integrity & Routing Validation",
        f"Generated: {datetime.now().isoformat()}",
        "=" * 70,
        "",
        "Brier Score: lower = better (0 = perfect). ~0.33 = random for 6 classes.",
        "ECE: Expected Calibration Error (mean |confidence - accuracy| over bins).",
        "",
        f"NOTE: SHAP explanations use '{FINAL_EXPLAIN_MODEL}' as surrogate for the",
        f"      deployed '{FINAL_PREDICT_MODEL}' predictor.",
        f"      Ensemble calibration: {'ON' if ENABLE_ENSEMBLE_CALIBRATION else 'OFF (default)'}.",
        "",
    ]

    fig_rows = len(results)
    if PLOT:
        fig, axes = plt.subplots(fig_rows, 1,
                                 figsize=(10, 4 * fig_rows), facecolor="white")
        if fig_rows == 1:
            axes = [axes]

    for ax_i, (name, res) in enumerate(results.items()):
        y_prob = res["y_prob"]
        y_pred = res["y_pred"]

        y_bin = label_binarize(y_test, classes=FAULT_LABELS)
        brier = np.mean([
            brier_score_loss(y_bin[:, i], y_prob[:, i])
            for i in range(len(FAULT_LABELS))
        ])

        max_conf = y_prob.max(axis=1)
        correct  = (y_pred == np.array(y_test)).astype(float)
        bins     = np.linspace(0, 1, 11)
        ece      = 0.0
        n_total  = len(y_test)
        bin_accs = []
        for lo, hi in zip(bins[:-1], bins[1:]):
            mask = (max_conf >= lo) & (max_conf < hi)
            n_b  = mask.sum()
            if n_b > 0:
                acc_b  = correct[mask].mean()
                conf_b = max_conf[mask].mean()
                ece   += n_b / n_total * abs(acc_b - conf_b)
                bin_accs.append(acc_b)
            else:
                bin_accs.append(0)

        report_lines += [
            f"--- {name} ---",
            f"  Brier Score : {brier:.4f}",
            f"  ECE         : {ece:.4f}",
            "",
        ]

        if PLOT:
            ax = axes[ax_i]
            bin_centers = [(bins[i] + bins[i+1]) / 2 for i in range(10)]
            ax.bar(bin_centers, bin_accs, width=0.09,
                   color="#2471A3", alpha=0.8, label="Accuracy")
            ax.plot([0, 1], [0, 1], "k--", lw=1, label="Perfect calibration")
            ax.set_xlabel("Confidence"); ax.set_ylabel("Accuracy")
            ax.set_title(f"Reliability Diagram — {name}  "
                         f"(Brier={brier:.3f}, ECE={ece:.3f})",
                         fontsize=10, fontweight="bold")
            ax.legend(fontsize=8); ax.grid(alpha=0.3)
            ax.set_xlim(0, 1); ax.set_ylim(0, 1)

    if PLOT:
        plt.tight_layout()
        p = os.path.join(OUT, "calibration_reliability.png")
        plt.savefig(p, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  Plot: {p}")

    cal_path = os.path.join(OUT, "calibration_report.txt")
    with open(cal_path, "w") as f:
        f.write("\n".join(report_lines))
    print(f"  Saved: {cal_path}")


# ── LEAKAGE AUDIT ─────────────────────────────────────────────────────────────
def audit_feature_leakage(X, y, feat_cols, le):
    print("\n  [Leakage Audit] Computing mutual information...")
    y_enc = le.transform(y)
    mi    = mutual_info_classif(X, y_enc, random_state=42)
    idx   = np.argsort(mi)[::-1][:15]

    audit_path = os.path.join(OUT, "leakage_audit.txt")
    with open(audit_path, "w") as f:
        f.write("FEATURE LEAKAGE AUDIT — v6.1\n")
        f.write("=" * 60 + "\n")
        f.write("worst_node_idx REMOVED from training (FIX-A).\n")
        f.write("severity / fault_detected excluded (analysis-only cols).\n")
        f.write("signal_uniformity = mean(per-branch variance) (FIX-B).\n")
        f.write("Temporal features scaled separately before selection (FIX-8).\n\n")
        f.write(f"{'Rank':<6} {'Feature':<34} {'MI Score':<12} {'Risk'}\n")
        f.write("-" * 60 + "\n")
        HIGH_MI = ["worst_node_isolation", "routing_signature", "cross_coupling_estimate"]
        for rank, i in enumerate(idx, 1):
            fname = feat_cols[i]
            risk  = "REVIEW" if fname in HIGH_MI else "OK"
            f.write(f"{rank:<6} {fname:<34} {mi[i]:<12.4f} {risk}\n")
    print(f"  Saved: {audit_path}")
    return mi


# ── SAVE ARTIFACTS ────────────────────────────────────────────────────────────
def save_best_model(results, scaler, feat_cols, le, selector=None,
                    temporal_scaler=None, loc_model=None):
    best = max(results, key=lambda k: results[k]["acc"])
    b    = results[best]
    print(f"\nBest model: {best} ({b['acc'] * 100:.2f}%)")

    artifacts = [
        ("best_model.pkl",    b["model"]),
        ("scaler.pkl",        scaler),
        ("label_encoder.pkl", le),
        ("model_metadata.pkl", {
            "best_model_name":    best,
            "accuracy":           b["acc"],
            "acc_confident":      b["acc_thresh"],
            "feature_cols":       feat_cols,
            "classes":            FAULT_LABELS,
            "location_classes":   LOCATION_LABELS,
            "needs_scaling":      False,
            "conf_threshold":     CONFIDENCE_THRESHOLD,
            "dataset_version":    "v6",
            "classifier_version": "v6.1",
            "trained_at":         datetime.now().isoformat(),
            "feature_count":      len(feat_cols),
            "leakage_removed":    True,
            "worst_node_idx_removed": True,
            "num_nodes_total":    12,
            "num_harness_nodes":  11,
            "shap_surrogate_model": FINAL_EXPLAIN_MODEL,
            "predict_model":      FINAL_PREDICT_MODEL,
            "ensemble_calibration_enabled": ENABLE_ENSEMBLE_CALIBRATION,
            "has_temporal":       any("_tmean" in c for c in feat_cols),
            "has_selector":       selector is not None,
            "n_temporal_steps":   N_TEMPORAL_STEPS,
            "fixes_applied": [
                "FIX-1", "FIX-2", "FIX-3", "FIX-4", "FIX-5",
                "FIX-6", "FIX-7", "FIX-8", "FIX-9", "FIX-10",
                "FIX-A", "FIX-B", "FIX-C", "FIX-D",
                "FIX-E", "FIX-F", "FIX-G", "FIX-H",
            ],
            "mcc":     b["mcc"],
            "roc_auc": b["auc"],
        }),
    ]

    # FIX-9: save selector and temporal scaler for use in inference/dashboard
    if selector is not None:
        artifacts.append(("selector.pkl", selector))
    if temporal_scaler is not None:
        artifacts.append(("temporal_scaler.pkl", temporal_scaler))
    if loc_model is not None:
        artifacts.append(("location_model.pkl", loc_model))

    for fname, obj in artifacts:
        p = os.path.join(OUT, fname)
        with open(p, "wb") as f:
            pickle.dump(obj, f)
        print(f"  Saved: {fname}")
    return best


def save_feature_ranking(results, feat_cols):
    rf = results.get("Random Forest", {}).get("model")
    if rf is None or not hasattr(rf, "feature_importances_"):
        return
    imp = rf.feature_importances_
    idx = np.argsort(imp)[::-1]
    path = os.path.join(OUT, "top_features.csv")
    V4_FEATS = {"routing_signature", "branch_symmetry_error",
                "isolation_index", "signal_uniformity",
                "max_branch_delta", "cross_coupling_estimate"}
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Rank", "Feature", "Importance", "Cumulative_%", "Category"])
        cumsum = 0.0
        for rank, i in enumerate(idx, 1):
            cumsum += imp[i]
            fname  = feat_cols[i]
            cat    = ("Temporal"   if any(s in fname for s in ["_tmean","_tstd","_tdelta","_trange"]) else
                      "Voltage"    if fname.startswith("V_N") else
                      "Deviation"  if fname.startswith("DEV_") else
                      "Current"    if fname.startswith("I_N") else
                      "Routing_v4" if fname in V4_FEATS else
                      "Engineered")
            w.writerow([rank, fname, f"{imp[i]:.6f}",
                        f"{cumsum * 100:.2f}%", cat])
    print(f"  Saved: {path}")


def save_model_accuracy_csv(results):
    path = os.path.join(OUT, "model_accuracy.csv")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Model", "Test_Accuracy_%", "CV_Accuracy_%", "CV_Std_%",
                    "Confident_Accuracy_%", "Uncertain_Count", "MCC", "ROC_AUC_OvR"])
        for name, res in results.items():
            w.writerow([
                name,
                f"{res['acc'] * 100:.2f}",
                f"{res['cv_mean'] * 100:.2f}",
                f"{res['cv_std'] * 100:.2f}",
                f"{res['acc_thresh'] * 100:.2f}",
                res["n_uncertain"],
                f"{res['mcc']:.4f}",
                f"{res['auc']:.4f}" if not np.isnan(res['auc']) else "N/A",
            ])
    print(f"  Saved: {path}")


def save_text_report(results, feat_cols, best_name, mi=None):
    path = os.path.join(OUT, "classification_report.txt")
    with open(path, "w") as f:
        # FIX-10: version bump to v6.1
        f.write("=" * 70 + "\n")
        f.write("HARNESS FAULT CLASSIFIER v6.1 — EVALUATION REPORT\n")
        f.write("AI-Driven Pre-ECU Harness Integrity & Routing Validation\n")
        f.write("Ashok Leyland — Chassis Assembly Line 2\n")
        f.write(f"Generated: {datetime.now().isoformat()}\n")
        f.write("=" * 70 + "\n\n")
        # FIX-G: corrected accuracy wording
        f.write("Performance summary:\n")
        f.write("  ~86% overall test accuracy; ~99% accuracy on high-confidence\n")
        f.write("  predictions (confidence >= 75%). UNCERTAIN returned otherwise.\n\n")
        # FIX-H: node count clarification
        f.write("Topology: 1 source/fusebox node (N0) + 11 harness measurement\n")
        f.write("  nodes (N1-N11). NUM_NODES=12 refers to total including source.\n\n")
        # FIX-D: SHAP surrogate note
        f.write(f"Explainability: SHAP computed on '{FINAL_EXPLAIN_MODEL}' (surrogate).\n")
        f.write(f"  Final predictions use '{FINAL_PREDICT_MODEL}'.\n")
        f.write(f"  Ensemble calibration: {'ON' if ENABLE_ENSEMBLE_CALIBRATION else 'OFF (default — use for publication runs only)'}.\n\n")
        f.write(f"Classes ({len(FAULT_LABELS)}): {', '.join(FAULT_LABELS)}\n")
        f.write(f"Feature set: {len(feat_cols)} features  [worst_node_idx removed v6]\n")
        f.write(f"Confidence threshold: {CONFIDENCE_THRESHOLD * 100:.0f}% (below = UNCERTAIN)\n\n")
        f.write("v6.1 fixes: temporal col naming, demo inference parity, selector.pkl\n"
                "            saved, persistence metric removed from eval, branch group\n"
                "            fix, ROC-AUC column ordering, temporal scaler, version bump.\n\n")

        for name, res in results.items():
            tag = " *** BEST ***" if name == best_name else ""
            f.write(f"\n{'=' * 50}\nMODEL: {name}{tag}\n{'=' * 50}\n")
            f.write(f"Test Accuracy       : {res['acc'] * 100:.2f}%\n")
            f.write(f"Confident Accuracy  : {res['acc_thresh'] * 100:.2f}%\n")
            f.write(f"CV Accuracy         : {res['cv_mean'] * 100:.2f}% "
                    f"+/- {res['cv_std'] * 100:.2f}%\n")
            f.write(f"UNCERTAIN readings  : {res['n_uncertain']}\n")
            f.write(f"MCC                 : {res['mcc']:.4f}\n")
            auc_str = f"{res['auc']:.4f}" if not np.isnan(res['auc']) else "N/A"
            f.write(f"ROC-AUC (OvR macro) : {auc_str}\n\n")
            f.write("Per-class confident accuracy:\n")
            for fl, cca in res["class_conf_acc"].items():
                val = f"{cca*100:.1f}%" if not np.isnan(cca) else "N/A"
                f.write(f"  {fl:<22}: {val}\n")
            f.write("\nClassification Report:\n" + res["cr"] + "\n")
            f.write("Confusion Matrix:\n")
            for i, row in enumerate(res["cm"]):
                f.write(f"  {FAULT_LABELS[i][:18]:<18}: {list(row)}\n")

        if mi is not None:
            f.write("\n" + "=" * 70 + "\nFEATURE LEAKAGE AUDIT\n" + "=" * 70 + "\n")
            f.write("(see leakage_audit.txt — worst_node_idx removed in v6)\n")

        f.write("\n" + "=" * 70 + "\nINFERENCE SNIPPET (v6.1)\n" + "=" * 70 + "\n")
        f.write("""
import pickle, numpy as np
from harness_classifier import FaultConfirmer, compute_physics_severity

with open('classifier_output/best_model.pkl','rb') as f:  model = pickle.load(f)
with open('classifier_output/model_metadata.pkl','rb') as f: meta = pickle.load(f)

# FIX-9: load selector if saved
selector = None
if meta.get('has_selector'):
    with open('classifier_output/selector.pkl','rb') as f: selector = pickle.load(f)

confirmer = FaultConfirmer(n_required=3)

feat_cols = meta['feature_cols']
# ... populate feat_dict with measured values (static + temporal stats) ...
X = np.array([feat_dict[c] for c in feat_cols]).reshape(1, -1)

# FIX-9: apply selector if present
if selector is not None:
    X = selector.transform(X)

pred  = model.predict(X)[0]
prob  = model.predict_proba(X).max()
label = pred if prob >= meta['conf_threshold'] else 'UNCERTAIN'
confirmed = confirmer.update(label)
print(f"Label: {label}  Confirmed: {confirmed}  Confidence: {prob*100:.1f}%")
""")
    print(f"  Saved: {path}")


# ── SHAP ──────────────────────────────────────────────────────────────────────
def run_shap(results, X_test, feat_cols, y_test, le):
    if not SHAP_OK or not PLOT:
        return
    print(f"\n  [SHAP] Surrogate model: '{FINAL_EXPLAIN_MODEL}'")
    print(f"         Prediction model: '{FINAL_PREDICT_MODEL}'")

    shap_results = {}

    for model_key, color in [("Random Forest", "#2471A3"), ("XGBoost", "#E67E22")]:
        res = results.get(model_key)
        if res is None:
            continue
        clf = res["model"]
        try:
            explainer = shap.TreeExplainer(clf)
            idx = np.random.choice(len(X_test), min(400, len(X_test)), replace=False)
            sv  = explainer.shap_values(X_test[idx])
            if isinstance(sv, list):
                shap_abs = np.abs(np.array(sv)).mean(axis=0).mean(axis=0)
            else:
                if sv.ndim == 3:
                    shap_abs = np.abs(sv).mean(axis=0).mean(axis=1)
                else:
                    shap_abs = np.abs(sv).mean(axis=0)

            shap_results[model_key] = (shap_abs, idx, sv)

            top_n   = 20
            top_idx = np.argsort(shap_abs)[::-1][:top_n]
            fig, ax = plt.subplots(figsize=(13, 7), facecolor="white")
            ax.barh(range(top_n), shap_abs[top_idx[::-1]], color=color, alpha=0.85)
            ax.set_yticks(range(top_n))
            ax.set_yticklabels([feat_cols[i] for i in top_idx[::-1]], fontsize=9)
            ax.set_xlabel("Mean |SHAP value|", fontsize=11)
            ax.set_title(
                f"SHAP Feature Importance — {model_key} "
                f"(surrogate for {FINAL_PREDICT_MODEL})\n"
                "(avg over all 6 fault classes)",
                fontsize=10, fontweight="bold")
            ax.grid(axis="x", alpha=0.3)
            plt.tight_layout()
            p = os.path.join(OUT, f"shap_{model_key.lower().replace(' ', '_')}.png")
            plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
            print(f"  Plot: {p}")
        except Exception as e:
            print(f"  [SHAP] {model_key} error: {e}")

    if "Random Forest" in shap_results and "XGBoost" in shap_results:
        try:
            rf_abs  = shap_results["Random Forest"][0]
            xgb_abs = shap_results["XGBoost"][0]
            top_n   = 15
            combined = rf_abs + xgb_abs
            top_idx  = np.argsort(combined)[::-1][:top_n]
            labels   = [feat_cols[i] for i in top_idx[::-1]]

            fig, ax = plt.subplots(figsize=(14, 8), facecolor="white")
            y_pos = np.arange(top_n)
            ax.barh(y_pos - 0.2, rf_abs[top_idx[::-1]],  0.38,
                    color="#2471A3", alpha=0.85, label="Random Forest")
            ax.barh(y_pos + 0.2, xgb_abs[top_idx[::-1]], 0.38,
                    color="#E67E22", alpha=0.85, label="XGBoost")
            ax.set_yticks(y_pos); ax.set_yticklabels(labels, fontsize=9)
            ax.set_xlabel("Mean |SHAP value|", fontsize=11)
            ax.set_title(
                f"SHAP Comparison — RF vs XGB (surrogates for {FINAL_PREDICT_MODEL})\n"
                "top-15 features; worst_node_idx removed in v6",
                fontsize=10, fontweight="bold")
            ax.legend(fontsize=9); ax.grid(axis="x", alpha=0.3)
            plt.tight_layout()
            p = os.path.join(OUT, "shap_comparison_rf_xgb.png")
            plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
            print(f"  Plot: {p}")
        except Exception as e:
            print(f"  [SHAP] comparison error: {e}")

    rf_res = results.get("Random Forest")
    if rf_res and "Random Forest" in shap_results:
        clf = rf_res["model"]
        _, idx, sv = shap_results["Random Forest"]
        if isinstance(sv, list):
            class_names = clf.classes_.tolist()
            for target in ["ROUTING_MISMATCH", "WIRE_WIRE_SHORT"]:
                if target not in class_names:
                    continue
                cidx   = class_names.index(target)
                sv_cls = np.array(sv)[cidx]
                top15  = np.argsort(np.abs(sv_cls).mean(axis=0))[::-1][:15]
                fig, ax = plt.subplots(figsize=(12, 6), facecolor="white")
                ax.barh(range(15),
                        np.abs(sv_cls).mean(axis=0)[top15[::-1]],
                        color="#E74C3C" if target == "ROUTING_MISMATCH" else "#5B3FA6",
                        alpha=0.85)
                ax.set_yticks(range(15))
                ax.set_yticklabels([feat_cols[i] for i in top15[::-1]], fontsize=9)
                ax.set_xlabel("Mean |SHAP value|", fontsize=10)
                ax.set_title(f"SHAP — {target} class (top-15 drivers)",
                             fontsize=11, fontweight="bold")
                ax.grid(axis="x", alpha=0.3)
                plt.tight_layout()
                p2 = os.path.join(OUT, f"shap_{target.lower()}.png")
                plt.savefig(p2, dpi=150, bbox_inches="tight"); plt.close()
                print(f"  Plot: {p2}")


# ── PLOTS ─────────────────────────────────────────────────────────────────────
def plot_confusion_matrices(results):
    if not PLOT: return
    n = len(results); cols = min(n, 3); rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols,
                             figsize=(7 * cols, 6 * rows), facecolor="white")
    axes = np.array(axes).flatten()
    short = [l[:5] for l in FAULT_LABELS]
    for ax, (name, res) in zip(axes, results.items()):
        cm  = res["cm"].astype(float)
        cmn = cm / cm.sum(axis=1, keepdims=True)
        im  = ax.imshow(cmn, cmap="Blues", vmin=0, vmax=1)
        plt.colorbar(im, ax=ax)
        ax.set_xticks(range(len(FAULT_LABELS))); ax.set_yticks(range(len(FAULT_LABELS)))
        ax.set_xticklabels(short, rotation=35, fontsize=8)
        ax.set_yticklabels(short, fontsize=8)
        ax.set_xlabel("Predicted"); ax.set_ylabel("Actual")
        ax.set_title(f"{name} — {res['acc'] * 100:.1f}%  MCC={res['mcc']:.3f}",
                     fontsize=10, fontweight="bold")
        for i in range(len(FAULT_LABELS)):
            for j in range(len(FAULT_LABELS)):
                ax.text(j, i, str(res["cm"][i][j]), ha="center", va="center",
                        fontsize=8,
                        color="white" if cmn[i, j] > 0.5 else "black")
    for ax in axes[len(results):]:
        ax.axis("off")
    plt.suptitle("Confusion Matrices — 6-Class Harness Fault Classifier v6.1",
                 fontsize=14, fontweight="bold")
    plt.tight_layout()
    p = os.path.join(OUT, "confusion_matrix.png")
    plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
    print(f"  Plot: {p}")


def plot_feature_importance(results, feat_cols):
    if not PLOT: return
    rf = results.get("Random Forest", {}).get("model")
    if rf is None or not hasattr(rf, "feature_importances_"):
        return
    imp = rf.feature_importances_
    idx = np.argsort(imp)[::-1][:20]
    top = [feat_cols[i] for i in idx]
    vals = imp[idx]
    V4_FEATS = {"routing_signature", "branch_symmetry_error", "isolation_index",
                "signal_uniformity", "max_branch_delta", "cross_coupling_estimate"}
    TEMP_SUFFIXES = ("_tmean", "_tstd", "_tdelta", "_trange")
    colors = []
    for fn in top:
        if any(fn.endswith(s) for s in TEMP_SUFFIXES): colors.append("#FF9F1C")
        elif fn in V4_FEATS:          colors.append("#FF6B35")
        elif "DEV" in fn:             colors.append("#C0392B")
        elif fn.startswith("V_N"):    colors.append("#2471A3")
        elif fn.startswith("I_N"):    colors.append("#27AE60")
        else:                         colors.append("#B86B00")
    fig, ax = plt.subplots(figsize=(13, 8), facecolor="white")
    ax.barh(range(len(top)), vals[::-1], color=colors[::-1], alpha=0.85)
    ax.set_yticks(range(len(top)))
    ax.set_yticklabels(top[::-1], fontsize=9)
    ax.set_xlabel("Gini Importance", fontsize=11)
    ax.set_title(
        "Top 20 Feature Importances — Random Forest v6.1\n"
        "(temporal cols named | worst_node_idx removed | signal_uniformity=mean(branch-var))",
        fontsize=11, fontweight="bold")
    ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()
    p = os.path.join(OUT, "feature_importance.png")
    plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
    print(f"  Plot: {p}")


def plot_model_comparison(results):
    if not PLOT: return
    names = list(results.keys())
    accs  = [results[n]["acc"]        * 100 for n in names]
    acct  = [results[n]["acc_thresh"] * 100 for n in names]
    cvs   = [results[n]["cv_mean"]    * 100 for n in names]
    stds  = [results[n]["cv_std"]     * 100 for n in names]
    x = np.arange(len(names)); w = 0.26
    fig, ax = plt.subplots(figsize=(14, 6), facecolor="white")
    b1 = ax.bar(x - w, accs, w, label="Test Accuracy",  color="#1A7A6E", alpha=0.85)
    ax.bar(x,     acct, w, label=f"Confident Acc (>{CONFIDENCE_THRESHOLD*100:.0f}%)",
           color="#C0392B", alpha=0.85)
    ax.bar(x + w, cvs,  w, label="CV Accuracy",  color="#2471A3", alpha=0.85,
           yerr=stds, capsize=4)
    ax.set_xticks(x); ax.set_xticklabels(names, fontsize=9, rotation=15)
    ax.set_ylabel("Accuracy (%)"); ax.set_ylim(60, 108)
    ax.set_title("Model Comparison — v6.1 (temporal cols fixed | selector.pkl saved)",
                 fontsize=12, fontweight="bold")
    ax.legend(fontsize=9); ax.grid(axis="y", alpha=0.3)
    for bar, v in zip(b1, accs):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
                f"{v:.1f}%", ha="center", fontsize=8, fontweight="bold")
    plt.tight_layout()
    p = os.path.join(OUT, "model_comparison.png")
    plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
    print(f"  Plot: {p}")


def plot_pca(X_test, y_test, feat_cols):
    if not PLOT: return
    pca = PCA(n_components=2, random_state=42)
    X2d = pca.fit_transform(X_test)
    fig, ax = plt.subplots(figsize=(12, 8), facecolor="white")
    for fid, label in enumerate(FAULT_LABELS):
        mask = y_test == label
        ax.scatter(X2d[mask, 0], X2d[mask, 1],
                   c=COLORS[fid], label=label, alpha=0.45, s=18, edgecolors="none")
    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
    ax.set_title("PCA — 6-Class Fault Separation v6.1", fontsize=12, fontweight="bold")
    ax.legend(fontsize=9, markerscale=2); ax.grid(alpha=0.2)
    plt.tight_layout()
    p = os.path.join(OUT, "fault_decision_boundaries.png")
    plt.savefig(p, dpi=150, bbox_inches="tight"); plt.close()
    print(f"  Plot: {p}")


# ── FIX-2 + FIX-6: DEMO INFERENCE ────────────────────────────────────────────
def demo_inference(results, feat_cols, le, selector=None, static_col_names=None):
    """
    FIX-2: featurise() now produces EXACTLY len(feat_cols) features by
           including temporal statistics (4 stats × 11 nodes = 44 cols)
           computed from a short simulated sequence — same as training pipeline.
    FIX-6: Branch groups corrected to [0,1,2],[3,4,5],[6,7,8],[9,10]
           matching the generator's BRANCH_GROUPS exactly.
    """
    model_name = (FINAL_PREDICT_MODEL if FINAL_PREDICT_MODEL in results
                  else "Random Forest")
    clf    = results[model_name]["model"]
    is_xgb = results[model_name].get("is_xgb", False)
    ref    = [4.9992, 4.9992, 4.9991, 4.9989, 4.9988,
              4.9988, 4.9987, 4.9987, 4.9985, 4.9984, 4.9982]

    # FIX-6: corrected branch groups (match generator BRANCH_GROUPS exactly)
    BRANCH_GROUPS_IDX = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10]]

    def featurise(V11):
        V    = np.array(V11)
        r    = np.array(ref)
        devs = [(v - rv) / rv * 100 if abs(rv) > 1e-6 else -100.0
                for v, rv in zip(V, r)]
        sl   = 1000.0
        cur  = [V[n - 1] / sl * 1000 for n in [2, 3, 5, 6, 8, 9, 11]]
        da   = [abs(d) for d in devs]
        wi   = int(np.argmax(da))
        oth  = [da[k] for k in range(len(da)) if k != wi]

        routing_sig  = abs(V[1]-V[2]) + abs(V[4]-V[5]) + abs(V[7]-V[8])

        # FIX-6: corrected branch groups
        branch_means = [float(np.mean(V[g])) for g in BRANCH_GROUPS_IDX]
        branch_sym   = float(np.std(branch_means))
        vmax         = float(V.max())
        iso_idx      = float(V.min()) / vmax if vmax > 1e-6 else 0.0
        pairs        = [(1, 2), (4, 5), (7, 8)]
        cross        = float(np.mean([abs(devs[a]-devs[b]) for a, b in pairs]))

        # FIX-B: signal_uniformity = mean of per-branch variance
        branch_vars = [float(np.var(V[g])) for g in BRANCH_GROUPS_IDX if len(g) > 1]
        sig_unif    = float(np.mean(branch_vars)) if branch_vars else 0.0

        max_bd = 0.0
        for g in BRANCH_GROUPS_IDX:
            if len(g) > 1:
                max_bd = max(max_bd, float(V[g].max() - V[g].min()))

        # Static engineered features (in the same order as extract_features)
        # FIX-A: worst_node_idx removed
        eng = [
            V.min(), V.max(), V.max()-V.min(), V.mean(), V.std(),
            max(da), sum(1 for d in da if d > 8.0),
            abs(V[4]-V[5]), abs(V[1]-V[2]), abs(V[7]-V[8]),
            da[wi] - np.mean(oth) if oth else da[wi], 35.0,
            routing_sig, branch_sym, iso_idx, sig_unif, max_bd, cross,
        ]
        static_feats = list(V) + devs + cur + eng

        # FIX-2: generate temporal stats from a short simulated sequence
        # (small perturbations around the given voltages, same as training)
        temporal_feats = []
        for n_idx in range(11):
            base_v = V[n_idx]
            seq = np.array([base_v + np.random.normal(0, 0.0005)
                            for _ in range(N_TEMPORAL_STEPS)])
            temporal_feats.extend([
                float(seq.mean()),
                float(seq.std()),
                float(seq[-1] - seq[0]),
                float(seq.max() - seq.min()),
            ])

        all_feats = static_feats + temporal_feats
        return all_feats, devs, routing_sig, branch_sym, iso_idx

    cases = [
        ("Healthy harness",        "HEALTHY",
         [4.9992,4.9992,4.9991,4.9989,4.9988,4.9988,4.9987,4.9987,4.9985,4.9984,4.9982]),
        ("Open circuit at N2",     "OPEN_CIRCUIT",
         [4.9992,0.0001,4.9991,4.9989,4.9988,4.9988,4.9987,4.9987,4.9985,4.9984,4.9982]),
        ("Short to GND at N4",     "SHORT_TO_GROUND",
         [2.8123,2.8122,2.8122,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001]),
        ("Routing mismatch N2-N3", "ROUTING_MISMATCH",
         [4.9992,3.1500,5.5000,4.9989,4.9988,4.9988,4.9987,4.9987,4.9985,4.9984,4.9982]),
        ("High resistance N7-N8",  "HIGH_RESISTANCE",
         [4.9992,4.9992,4.9991,4.9989,4.9988,4.9988,4.2000,4.9987,4.9985,4.9984,4.9982]),
    ]

    confirmer = FaultConfirmer(n_required=3)
    print("\n" + "=" * 60)
    print(f"INFERENCE DEMO — {model_name}  [v6.1]")
    print(f"SHAP surrogate: {FINAL_EXPLAIN_MODEL}")
    print(f"Feature vector length: {len(feat_cols)} (static + temporal)")
    print("=" * 60)

    for desc, expected, V11 in cases:
        feats, devs, rs, bs, ii = featurise(V11)

        # Build feature vector aligned to feat_cols
        X_vec = np.array(feats).reshape(1, -1)

        # FIX-9: apply selector if provided
        if selector is not None:
            X_vec = selector.transform(X_vec)
        else:
            # Fallback: truncate/pad to feat_cols length
            if X_vec.shape[1] > len(feat_cols):
                X_vec = X_vec[:, :len(feat_cols)]
            elif X_vec.shape[1] < len(feat_cols):
                pad = np.zeros((1, len(feat_cols) - X_vec.shape[1]))
                X_vec = np.hstack([X_vec, pad])

        if is_xgb:
            pred = le.inverse_transform([clf.predict(X_vec)[0]])[0]
        else:
            pred = clf.predict(X_vec)[0]

        prob  = clf.predict_proba(X_vec).max()
        final = pred if prob >= CONFIDENCE_THRESHOLD else "UNCERTAIN"
        confirmed = confirmer.update(final)
        # FIX-C: physics severity
        sev = compute_physics_severity(devs, bs, ii, rs)
        match = "OK" if pred == expected else "MISMATCH"
        print(f"\n  [{match}] {desc}")
        print(f"    Expected:  {expected}")
        print(f"    Predicted: {pred}  ({prob*100:.1f}%)")
        print(f"    Final:     {final}  | Confirmed: {confirmed}")
        print(f"    Severity:  {sev}%  (physics-informed)")


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("HARNESS FAULT CLASSIFIER v6.1")
    print("AI-Driven Pre-ECU Harness Integrity & Routing Validation")
    print("Ashok Leyland — Chassis Assembly Line 2")
    print("=" * 60)
    print("v6.1: temporal col naming | demo inference fix | selector.pkl saved")
    print("      persistence metric removed | branch groups fixed | ROC-AUC col order\n")

    rows = load_data(DATASET_PATH)

    # FIX-1 + FIX-3: extract with fully-named feat_cols (static + temporal)
    X, y, feat_cols, static_cols, temporal_cols = extract_features(rows, "engineered")
    y_loc = extract_location_labels(rows)

    print(f"  Features: {len(feat_cols)} "
          f"({len(static_cols)} static + {len(temporal_cols)} temporal)  |  Samples: {len(X)}")
    print(f"  Excluded: severity, fault_detected, worst_node_idx")
    print(f"  Classes: {Counter(y)}")
    print(f"  Location classes: {Counter(y_loc)}")

    le = LabelEncoder()
    le.fit(FAULT_LABELS)
    y_enc_temp = LabelEncoder().fit_transform(y)

    # FIX-8: scale temporal features separately before SelectKBest
    # to prevent temporal statistics from dominating static features
    n_static   = len(static_cols)
    n_temporal = len(temporal_cols)
    temporal_scaler = None
    if n_temporal > 0:
        temporal_scaler = StandardScaler()
        X[:, n_static:] = temporal_scaler.fit_transform(X[:, n_static:])
        print(f"  Temporal features normalised separately (FIX-8)")

    # FIX-3: SelectKBest on fully-named feat_cols → get_support maps correctly
    k_best = min(60, X.shape[1])
    selector = SelectKBest(score_func=mutual_info_classif, k=k_best)
    X = selector.fit_transform(X, y_enc_temp)
    feat_cols = [feat_cols[i] for i in selector.get_support(indices=True)]
    print(f"  Feature selection applied -> {len(feat_cols)} features retained")

    assert X.shape[1] == len(feat_cols), (
        f"[BUG POST-SELECT] X.shape[1]={X.shape[1]} != len(feat_cols)={len(feat_cols)}"
    )

    X_tr, X_te, y_tr, y_te, yl_tr, yl_te = train_test_split(
        X, y, y_loc, test_size=0.2, random_state=42, stratify=y)
    print(f"  Train: {len(X_tr)}  |  Test: {len(X_te)}")

    results, scaler = train_evaluate(X_tr, X_te, y_tr, y_te, feat_cols, le)

    loc_model = train_location_model(X_tr, yl_tr)
    from sklearn.metrics import accuracy_score as _acc
    loc_acc = _acc(yl_te, loc_model.predict(X_te))
    print(f"  Location predictor accuracy: {loc_acc*100:.1f}%")

    # FIX-9: pass selector and temporal_scaler to save_best_model
    best_name = save_best_model(results, scaler, feat_cols, le,
                                selector=selector,
                                temporal_scaler=temporal_scaler,
                                loc_model=loc_model)
    mi = audit_feature_leakage(X, y, feat_cols, le)
    save_text_report(results, feat_cols, best_name, mi)
    save_feature_ranking(results, feat_cols)
    save_model_accuracy_csv(results)

    print("\nGenerating plots...")
    plot_confusion_matrices(results)
    plot_feature_importance(results, feat_cols)
    plot_model_comparison(results)
    plot_pca(X_te, y_te, feat_cols)

    print("\nCalibration diagnostics...")
    run_calibration_diagnostics(results, y_te)

    print("\nRunning SHAP (surrogate: RF + XGB)...")
    run_shap(results, X_te, feat_cols, y_te, le)

    # FIX-2: pass selector so demo inference aligns feature space correctly
    demo_inference(results, feat_cols, le,
                   selector=selector,
                   static_col_names=static_cols)

    print(f"\nAll outputs -> {OUT}/")
    print("Next: python harness_dashboard.py --static")


if __name__ == "__main__":
    main()
